---
- name: declaring the variables at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: printing the variable
      ansible.builtin.debug:
        - msg: URL == {{URL}}


- name: Declaring variables at the play level from another file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    name: printing the variable
    ansible.builtin.debug:
      msg: URL == {{URL}}



- name: declaring the variables at task level
  hosts: all
  connection: local
  tasks:
    - name: printing the variable
      ansible.builtin.debug:
        - msg: URL == {{URL}}
      vars:
          URL: play.example.com





