- name: declaring the variables at task level
  hosts: all
  connection: local
  tasks:
     - name: printing
       ansible.builtin.debug:
          msg: "URL == {{URL}}"
       vars:
          URL: task.example.com