- name: Register a variable
  hosts: all
  connection: local
  tasks:
    - name: run a shell script
      ansible.builtin.shell: uptime
      register: out
    - name: print out
      ansible.builtin.debug:
        msg: "{{out}}"
    - name: Set a fact
      ansible.builtin.set_fact:
        OUTPUT: "{{out.stdout}}"